    print("hello word")
    print("许政泽")
    print("   *")
    print("  ***")
    print(" *****")
    print("*******")
    X=100
    print(X)
    YOU=input("请输入:")
    print(YOU)
    LOL=int(input("请输入:"))
    print(LOL)
    DNM=int(input("请输入："))
    print(DNM)
    print("他们的和为：",LOL+DNM)
